sonar.host.url=http://localhost:9000
sonar.projectKey=web-analysis-angular
sonar.projectName=web-analysis-angular
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/tests/**,**/main.ts,**/app/app.routes.ts,**/src/environments/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/web-app/lcov-report/lcov.info
sonar.login=sqa_40afc2362caf79c2219855c1d6d35bdf3f26c2be